// document.write("hello Dom");
// const x = "hello world";
// document.getElementById("idOne").innerText = "helloworld";
// let myValue = document.getElementById("idOne").textContent;
// console.log(myValue);
// //console.warn("c% color:green,Hello");
// console.dir(document.body);
const hh = document.querySelector("#header");
hh.textContent = "New Header";
const getID = document.getElementById("header");
getID.textContent = "New value";
const getTag = document.getElementsByTagName("li");
getTag[3].textContent = "UPDATED-----";
const el1 = document.querySelector("h1");
console.log(el1);
const el2 = document.querySelector(".row");
console.log(el2);
const el3 = document.querySelector("#header");
console.log(el1);
el1.textContent = "HELLO";
console.log(el3.textContent);
